MoneyRemittance.web/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoneyRemittance.web.Controllers
{
    public class ContactUsController : Controller
    {
        /// <summary>
        /// Contact Us Controller
        /// </summary>
        /// <returns></returns>

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Message1 = "We're here to help";

            //Sample
            //IndexViewModel viewModel = new IndexViewModel();
            //viewModel.Countries = new SelectList(GetCountries(), "ID", "Name");

            return View();
        }

        [HttpPost]
        public ActionResult Index()
        {

            //Sample
            //viewModel.Countries = new SelectList(GetCountries(), "ID", "Name");
            //if (!ModelState.IsValid)
            //    return View(viewModel);

            ////TODO: Do something with the selected country...
            //CMSService.UpdateCurrentLocation(viewModel.CountryID);

            return View(viewModel);

            return View();
        }

        public ActionResult Follow()
        {
            ViewBag.Message = "Follow Us at Twitter, Facebook or Linkedin";
            return View();
        }

        [HttpGet]
        [ChildActionOnly]
        public ActionResult _Create()
        {
            return PartialView("_Create");
        }
    }
}

MoneyRemittance.web/Controllers/DisclaimerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoneyRemittance.web.Controllers
{
    public class DisclaimerController : Controller
    {
        //
        // GET: /Disclaimer/

        public ActionResult Index()
        {
            ViewBag.Message = "Security Disclaimer";
            return View();
        }

        public ActionResult Privacy()
        {
            ViewBag.Message = "Site Privacy";
            return View();
        }

        public ActionResult Agreement()
        {
            ViewBag.Message = "Rules and Agreement";
            return View();
        }

        public ActionResult Sitemap()
        {
            ViewBag.Message = "Sitemap";
            return View();
        }
    }
}

MoneyRemittance.web/Controllers/MainController.cs
using MoneyRemittance.model.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoneyRemittance.web.Controllers
{
    public class MainController : Controller
    {
        /// <summary>
        /// Money Remittance Main Controller 
        /// </summary>
        /// <returns></returns>

        public ActionResult Index()
        {
            ViewBag.message = "Online Money Remittance";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.message = "About Us";
            return View();
        }

        public ActionResult Support()
        {
            ViewBag.message = "Online Support for Money Remittance";
            return View();
        }

        public ActionResult Prices()
        {
            ViewBag.message = "Money Remittance Pricing";
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

MoneyRemittance.web/Controllers/SendMoneyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoneyRemittance.web.Controllers
{
    public class SendMoneyController : Controller
    {
        //
        // GET: /SendMoney/

        public ActionResult Index()
        {
            ViewBag.message = "Send Money Transaction";    
            return View();
        }

        //
        // GET: /SendMoney/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /SendMoney/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /SendMoney/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /SendMoney/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /SendMoney/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /SendMoney/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /SendMoney/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MoneyRemittance.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Online @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="header-wrapper">
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("logo here", "Index", "Main")</p>
                </div>
                <div class="float-right">                   
                    <nav>
                        <ul id="header-menu">
                            <li>@Html.ActionLink("Send Money", "Index", "SendMoney")</li>
                            <li>@Html.ActionLink("Create Account", "Index", "Customer")</li>
                            <li>@Html.ActionLink("Pricing", "Prices", "Main")</li>
                            <li>@Html.ActionLink("Support", "Support", "Main")</li>
                            <li>@Html.ActionLink("About", "About", "Main")</li>
                            <li>@Html.ActionLink("How to Start ?", "HowTo", "Helper")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </header>

    <div id="content">
        @RenderBody()       
        <section id="content-right-section">
            @RenderSection("CustomerRegister", required: false)
        </section>
    </div>

    <footer>
        <div class="footer-wrapper">
            <div class="content-wrapper">
                <div class="float-left">
                    <nav>
                        <ul class="footer-menu">
                            <li>@Html.ActionLink("Contact Us", "Index", "ContactUs")</li>
                            <li>@Html.ActionLink("Follow Us", "Follow", "ContactUs")</li>
                        </ul>
                    </nav>
                    <div>
                        <nav>
                            <ul class="footer-menu"">
                                <li>twitter</li>
                                <li>facebook</li>
                                <li>linkedin</li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="float-right">
                    <nav>
                        <ul class="footer-menu">
                            <li>@Html.ActionLink("Security", "Index", "Disclaimer")</li>
                            <li>@Html.ActionLink("Privacy", "Privacy", "Disclaimer")</li>
                            <li>@Html.ActionLink("User Agreement", "Agreement", "Disclaimer")</li>
                            <li>@Html.ActionLink("Site Map", "Sitemap", "Disclaimer")</li>
                        </ul>
                    </nav>
                    <span id="creator">&copy; @DateTime.Now.Year Powered by: <a href="http://www.transfigsoft.com/" target="_blank">Transfiguration Software</a></span>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bjqs")
    @RenderSection("scripts", required: false)
</body>
</html>